game/urls.py
from django.urls import path

from . import views

app_name = 'game'
urlpatterns = [
    path('categories/', views.category_view, name='categories'),
    path('play/<int:category_id>/', views.play_view, name='play'),
    path('check_answer/', views.check_answer, name='check_answer'),
]

trivia/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import landing_view, signup_view, login_view
from questions.views import category_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('questions/', include('questions.urls')), 
    path('', landing_view, name='landing'),
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('game/', include('game.urls')),
]

game/models.py
from django.db import models
from django.contrib.auth.models import User
from questions.models import Category, Question

# Create your models here.

class Game(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    questions = models.ManyToManyField(Question)
    current_question = models.ForeignKey(Question, on_delete=models.SET_NULL, null=True, related_name='+')
    score = models.IntegerField(default=0)
    questions_answered = models.IntegerField(default=0)

game/views.py
from django.http import JsonResponse
from django.shortcuts import render
from .models import Game
from questions.models import Question, Category
import random
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import json

# Create your views here.
def category_view(request):
    # Fetch or create your categories here
    categories = [{"id": 1, "name": "Sports"}, {"id": 2, "name": "Movies/TV"}, {"id": 3, "name": "Music"},{"id": 3, "name": "General Knowledge"}]
    return render(request, 'game/categories.html', {'categories': categories})

def play_view(request, category_id):
    # Retrieve the user and the category
    user = request.user
    category = Category.objects.get(id=category_id)
    game = Game.objects.filter(user=user, category=category).first()

    if game is None:
        game = Game.objects.create(user=user, category=category)

    if game.current_question is None:
        game.current_question = Question.objects.filter(category=category).exclude(id__in=game.questions.all()).order_by('?').first()
        game.save()

    print("Current question:", game.current_question)  # Print the current question

    # Create a list of answer choices for the current question
    question = game.current_question
    # Create a list of answer choices for the current question
    if game.current_question is not None:
        choices = [question.choice_1,
                   question.choice_2, 
                   question.choice_3, 
                   question.choice_4]

        correct_choice_index = int(game.current_question.correct_choice) - 1

        return render(request, 'game/play.html', {
        'game': game, 
        'choices': choices,
        'correct_choice_index': correct_choice_index
        })
    else:
        return render(request, 'game/play.html', {
        'game': game, 
        'error': "No question available"
        })


@login_required
@csrf_exempt
def check_answer(request):
    data = json.loads(request.body)
    answer_text = data.get('answer_text').strip()  # Using strip() function to remove spaces from both ends
    



    # Retrieve the game instance related to the current user
    game = Game.objects.filter(user=request.user).first()

    if game is None or game.current_question is None:
        # The game does not exist or has no current question
        return JsonResponse({'error': 'Game not found or no question to answer.'}, status=404)

    # Get choices for the current question
    choices = [game.current_question.choice_1,
               game.current_question.choice_2,
               game.current_question.choice_3,
               game.current_question.choice_4]
    
    # Get index of answer text in choices list
    answer_index = choices.index(answer_text) + 1  # +1 because choices are 1-indexed
    
    # Check if the answer is correct

    is_correct = (str(answer_index) == game.current_question.correct_choice)



    # Update the score if the answer is correct
    if is_correct:
        game.score += 10

    # Update the current question
    game.questions.add(game.current_question)
    game.questions_answered += 1
    game.current_question = Question.objects.filter(category=game.category).exclude(id__in=game.questions.all()).order_by('?').first()
    game.save()

    # Create a list of answer choices for the new question
    if game.current_question is not None:
        choices = [game.current_question.choice_1,
                   game.current_question.choice_2, 
                   game.current_question.choice_3, 
                   game.current_question.choice_4]

        correct_choice_index = int(game.current_question.correct_choice) - 1  # Get the index of the correct choice for the new question

        # Send back whether the answer was correct, the new question, correct choice index, and choices
        return JsonResponse({'is_correct': is_correct, 'question': game.current_question.question_text, 'correct_choice_index': correct_choice_index, 'choices': choices, 'score': game.score, 'questions_answered': game.questions.count()})
    else:
        # There are no more questions
        return JsonResponse({'is_correct': is_correct, 'error': 'No more questions available.', 'score': game.score, 'questions_answered': game.questions.count()})

game/templates/game/categories.html
{% extends 'accounts/base.html' %}

{% block content %}
<nav class="py-6 px-6 flex justify-center items-center border-b border-gray-200">
  <h1 class="trivia">
      <span>C</span>
      <span>a</span>
      <span>t</span>
      <span>e</span>
      <span>g</span>
      <span>o</span>
      <span>r</span>
      <span>i</span>
      <span>e</span>
      <span>s</span>
  </h1>
</nav>
<div class="grid grid-cols-2 gap-4">
  {% for category in categories %}
  <a href="{% url 'game:play' category.id %}" class="p-6 border border-gray-200 rounded-xl transition-colors duration-200 hover:bg-gray-300 block text-center">
    {{ category.name }}
  </a>
  {% endfor %}
</div>
{% endblock %}

game/templates/game/game_over.html
<!DOCTYPE html>
<html>
<head>
    <title>Game Over</title>
</head>
<body>
    <h1>Game Over</h1>
    <button id="restartButton">Restart Game</button>
    <button id="homeButton">Go Home</button>
    
    <script>
        document.getElementById('restartButton').addEventListener('click', function() {
            location.href = '/game/restart/';
        });
        
        document.getElementById('homeButton').addEventListener('click', function() {
            location.href = '/game/categories/';
        });
    </script>
</body>
</html>

game/templates/game/play.html
{% load static %}
{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'game.css' %}">

    <div class="container">
        <div class="game-info">
            <div class="question-number">
                Question: {{ game.questions.count|add:"1" }} / 20
            </div>
            <div class="timer-bar">
                <!-- This will be updated by JavaScript -->
                <div class="time-left"></div>
            </div>
            <div class="score">
                Score: {{ game.score }}
            </div>
        </div>
        <div class="question">
            <h2>{{ game.current_question }}</h2>
        </div>
        <div class="answers">
            {% for answer in choices %}
                <button class="answer" data-answer-id="{{ forloop.counter }}" style="color:black">
                    {{ answer }}
                </button>
            {% endfor %}


        </div>
        
    </div>
{% endblock %}

<script>
    var answerButtons = document.getElementsByClassName('answer');
    var questionElement = document.querySelector('.question h2');
    var scoreElement = document.querySelector('.score');
    var questionNumberElement = document.querySelector('.question-number');
    
    for (var i = 0; i < answerButtons.length; i++) {
        answerButtons[i].addEventListener('click', function(e) {
            e.preventDefault();
    
            for (var j = 0; j < answerButtons.length; j++) {
                answerButtons[j].disabled = true;
            }
    
            var clickedButton = this;
    
            fetch('{% url "game:check_answer" %}', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                body: JSON.stringify({
                    'answer_text': this.textContent.trim()
                })

    
            })
            .then(response => response.json())
            .then(data => {
                // Change color according to correctness
                console.log(data);
                if (data.is_correct) {
                    clickedButton.style.backgroundColor = 'green';
                } else {
                    clickedButton.style.backgroundColor = 'red';
                }
    
                // Delay for 3 seconds before updating question and choices
                setTimeout(function() {
                    if (!data.error) {
                        // Update the question text
                        questionElement.textContent = data.question;
    
                        // Update the score
                        scoreElement.textContent = 'Score: ' + data.score;
    
                        // Update the question number
                        // Update the question number
                        
                        questionNumberElement.textContent = 'Question: ' + (data.questions_answered + 1) + ' / 20';

                    
    
                        // Update the answer choices
                        for (var k = 0; k < answerButtons.length; k++) {
                            answerButtons[k].textContent = data.choices[k];
                            answerButtons[k].disabled = false;
                            answerButtons[k].style.backgroundColor = '#F0F0F0';
                            answerButtons[k].style.color = 'black';
    
                            if (k === data.correct_choice_index) {
                                answerButtons[k].dataset.isCorrect = 'true';
                            } else {
                                answerButtons[k].dataset.isCorrect = 'false';
                            }
                        }
                    } else {
                        // Handle error
                        console.error(data.error);
                    }
                }, 1000); // Delay of 3 seconds
            });
        });
    }
    </script>
    